apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: venvs-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/strivly/venvs.git
        revision: main
        directories:
          - path: "vclusters/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://charts.loft.sh
        targetRevision: 0.22.4
        chart: vcluster
        helm:
          parameters:
            - name: controlPlane.service.spec.type
              value: LoadBalancer
            - name: controlPlane.service.enabled
              value: 'true'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
